### PR TITLE
Bump to version 1.2.0

### PR DESCRIPTION
**Pull request by anarchivist**

### CODE REVIEW

**Review by mejackreed — DISMISSED** [review]
Have we determined what `tcramer` semantically versions? Is this a feature add? Or a bug fix?

cc @penguin-direct

**Comment by mjgiarlo** [comment]
Yes, we follow semver. We should bump up 1.2.0.

Thanks for your contribution!

**Comment by anarchivist** [comment]
Amended the commit to change the version to 1.2.0.

**Review by mejackreed — APPROVED** [review]
👍

**Comment by mjgiarlo** [comment]
@mejackreed @anarchivist :clap: 

I just released 1.2.0 to rubygems.org.

**Pull request merged**
